In [5]:
from utils import *
import numpy as np

dataset_names = ['CocitationCora', 'CocitationCiteseer', 'CoauthorshipCora', 'CoauthorshipDBLP', 'CocitationPubmed', 'Cooking200', 'Tencent2k']


for dataset in dataset_names:
    data = load_dataset(dataset)
    print(dataset)
    print(f"Number of classes : {data['num_classes']}")
    print(f"Number of nodes : {data['num_vertices']}")
    try:
        print(f"Feature size : {len(data['features'])}")
        print(data['features'].max(), data['features'].median(), data['features'].min())
        print(np.sum(data['features'].numpy(), axis = 0))
        print(np.sum(np.sum(data['features'].numpy(), axis = 0), axis = 0))
    except AssertionError as e:
        print(f"No features for dataset: {dataset}")
    print(f"Number of edges : {data['num_edges']}")
    print('\n')

CocitationCora
Number of classes : 7
Number of nodes : 2708
Feature size : 2708
tensor(1.) tensor(0.) tensor(0.)
[0.7399375  1.6960521  3.4994125  ... 0.36562112 3.2536626  0.61456096]
2708.0
Number of edges : 1579


CocitationCiteseer
Number of classes : 6
Number of nodes : 3312
Feature size : 3312
tensor(0.1250) tensor(0.) tensor(0.)
[0.5462797  2.3282082  0.3950563  ... 0.16268879 0.14603579 0.13409507]
3312.0
Number of edges : 1079


CoauthorshipCora
Number of classes : 7
Number of nodes : 2708
Feature size : 2708
tensor(1.) tensor(0.) tensor(0.)
[0.7399375  1.6960521  3.4994125  ... 0.36562112 3.2536626  0.61456096]
2708.0
Number of edges : 1072


CoauthorshipDBLP
Number of classes : 6
Number of nodes : 41302
Feature size : 41302
tensor(1.) tensor(0.) tensor(0.)
[11.581941 12.900859 32.922504 ... 42.192795 48.723064  3.      ]
41302.03
Number of edges : 22363


CocitationPubmed
Number of classes : 3
Number of nodes : 19717
Feature size : 19717
tensor(1.) tensor(0.) tensor(0.)
[0. 